server:
  port: 8080
spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/users
    driverClassName: org.postgresql.Driver
    username: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
